### ISSUE TITLE
slides_ensemble.ipynb

### ISSUE THREAD

**Issue by aleksmukhin** [stepthom/869_course#1]
Typo in the stacking:

from mlxtend.classifier import StackingClassifier
from sklearn.linear_model import LogisticRegression

clf1 = DecisionTreeClassifier(max_depth=4)
clf2 = KNeighborsClassifier(n_neighbors=7)
clf3 = SVC(kernel='rbf', probability=True)

classifiers=[('DT', clf1), ('KNN', clf2), ('SVM', clf3)]

sclf = StackingClassifier(
    classifiers=classifiers, meta_classifier=LogisticRegression(), 
    use_probas=True, average_probas=False)

clf1 = clf1.fit(X_train, y_train)
clf2 = clf2.fit(X_train, y_train)
clf3 = clf3.fit(X_train, y_train)
**sclf = cclf.fit(X_train, y_train)**

I think it should be sclf.fit(X_train, y_train) instead of sclf = cclf.fit(X_train, y_train)

Cheers

**Comment by stepthom** [comment]
Thanks, @aleksmukhin! Good catch. Fixed now.
